INSERT INTO USERCLASS (ID, NAME, ADMIN, MODERATOR) VALUES (1, "Admin", 1, 0)
INSERT INTO USERCLASS (ID, NAME, ADMIN, MODERATOR) VALUES (2, "Moderator", 0, 1)
INSERT INTO USERCLASS (ID, NAME, ADMIN, MODERATOR) VALUES (3, "User", 0, 0)
